### PR TITLE
Add Workflow->SubjectSet linking

### LINKED ISSUE #2: link subject sets to workflow
Provide ability to link subject set to a workflow, http://docs.panoptes.apiary.io/#reference/workflows/update-subject-set-links/update-subject-sets

Should get subject set copying for free with this.

### PR DESCRIPTION
**Pull request by astopy**
Closes #2

### CODE REVIEW

**Comment by astopy** [comment]
To test:

```python
>>> from panoptes_client import Panoptes, Project, SubjectSet, Workflow
>>> Panoptes.connect(username='...', password='...')
<panoptes_client.panoptes.Panoptes object at 0x10eb8e750>
>>> ss = SubjectSet.find(...)
>>> wf = Workflow.find(...)
>>> wf.add_subject_sets(ss)
>>> wf.remove_subject_sets(ss)
```

**Comment by camallen** [comment]
@astopy you cool with the hound errors?

**Comment by camallen** [comment]
LGTM

**Comment by astopy** [comment]
Yup, those errors are from Hound using Python 3.

**Pull request merged**
