### PR TITLE
add exportable behaviour to SubjectSet class

### PR DESCRIPTION
**Pull request by camallen**
Linked to the work in https://github.com/zooniverse/panoptes/pull/3719

Allow SubjectSet resource to generate their classification data exports

### CODE REVIEW

**Review by zwolf — APPROVED** [review]

**Comment by lcjohnso** [comment]
@camallen Can you add a usage example to the docs?  Or do you prefer to keep the functionality obscured initially?

**Review by lcjohnso — COMMENTED** [review]
@camallen Can you add a usage example to the docs? Or do you prefer to keep the functionality obscured initially?

**Comment by camallen** [comment]
Looks like the docs are auto updated based on the Exportable module inclusion to the SubjectSet class - https://panoptes-python-client.readthedocs.io/en/latest/panoptes_client.html#module-panoptes_client.subject_set

**Comment by camallen** [comment]
I could add something to https://panoptes-python-client.readthedocs.io/en/latest/user_guide.html#other-examples but there are no examples for existing resource (project / workflow) level exports as far as i can tell.

**Pull request merged**
