### PR TITLE
update readme to add the batch_size keyword for batch upload of subjects

### PR DESCRIPTION
**Pull request by mschwamb**
I needed to add the batch_size keyword to explicitly give the length of the list I added. Cam had mentioned this was faster.  I didn't see this example in the readme so I updated the one example ofa batch upload

### CODE REVIEW

**Comment by astopy** [comment]
I don't think we'd want to make this the default example. It'd be better to just increase the default batch size (currently 100) to something more sensible. I chose the default of 100 completely arbitrarily, so we can certainly find a more optimal number. 

There's a trade off between making bigger requests and smaller requests; bigger requests each take longer to process, but there's also certain amount of overhead per request. If the batch size is too big and the request takes more than a minute to process, the API's load balancer will drop the request and raise an error.

@camallen @marten @zwolf What are your thoughts on how big requests to Panoptes should be? The same default batch size is used for adding subjects to sets, adding to collections, retiring subjects, etc. (basically everywhere you can supply a list of things in a request). Should we tune it to be different for different things?

**Comment by marten** [comment]
Batch size definitely should just be the amount of things you're sending. That would break down if you tried to send in thousands of subjects.

100 would've been my initial guess for a default as well. Even for backgrounded API calls like retirement, Panoptes still has to fetch those 100 records from the database through layers of authentication/authorization before being able to plonk 100 jobs in Sidekiq. I wouldn't go too much higher. We have timeouts on API calls, but I don't see those as something we should try to get near to for batch API clients.

For scaling purposes it's probably better if requests are erring on the too-small side, since that means not locking up any web server thread for long, which is better for the group of online users as a whole. I would probably consider doing multiple requests concurrently before making them bigger.

**Comment by mschwamb** [comment]
So I think it's more the documentation isn't as clear as what to do and I've gotten differing suggestions from developers in the past about how to use the python tools. 

Typically I have an array of 1000 subjects (at least it was time). I was told I should add in the size of the array to the function call. Maybe that's no longer needed and batchsize is something different. 

If I want to create a set of 1000s subjects in a new subject set, what's the best way to do it?  Should I be having a loop and doing the one by one or if I just the batch call would that only upload 100 subjects?

**Comment by marten** [comment]
The way I understand it, the client would upload your 1000 subjects automatically without touching batchsize. The default of a 100 there means that the client will split it up into 10 requests to the API for you. @astopy ?

**Comment by astopy** [comment]
Yup. Just pass the whole list to `SubjectSet.add` and it'll automatically split it into batches if needed.

**Comment by mschwamb** [comment]
@astopy then I'll close this and add in a pull request to add a line that says something to that effect in the readme, which you can then decide to merge or not.

**Pull request closed without merging**
