### PR TITLE
Update readme docs 

### PR DESCRIPTION
**Pull request by camallen**
Add links to the wiki for more examples and add code on batch linking subjects to a set.

### CODE REVIEW

**Comment by astopy** [comment]
We actually have a read the docs page here http://panoptes-python-client.readthedocs.io/en/latest/index.html generated from the `docs` directory. I think I'd prefer it if we start putting stuff on there rather than in the readme and the GH wiki.

**Comment by camallen** [comment]
Can i sneak the linking in batches example into the readme to offset the example that is currently there? 

Also github wikis are normally collaborative so people can post their own examples for sharing. But that's up to you.

**Comment by astopy** [comment]
Sure, I would just simplify the example a little before adding it to the readme:

```python
# SubjectSet.add() can take a list of Subjects
subject_set.add([subject1, subject2, subject3])
# or just one at a time (but this is slower than doing several together)
subject_set.add(subject1)
subject_set.add(subject2)
```

I've removed the note about batch sizes -- the client handles batching automatically, regardless of how many objects are in the list.

I think it makes sense to keep everything in one place, and I'd like to start using RTD for the auto-generated reference documentation. People can always open PRs with more examples to add.

**Comment by camallen** [comment]
Updated the PR to include your comments.

**Pull request merged**
