### PR TITLE
Set member subject resources

### PR DESCRIPTION
**Pull request by camallen**
Provide a resource for the link between subject set and subjects and allow SubjectSet to return these linked resources.

Use the faster sms lookups for determining subject : set membership. E.g.

```
subject_set=SubjectSet.find(1)

for sms in subject_set.set_member_subjects():
    print("%s," % (sms.subject_id()))
```

### CODE REVIEW

**Comment by camallen** [comment]
Adding a note that paging over the `SubjectSet.subjects()` resources times out on the API due to the join filtering between the subjects / sms. 
> panoptes_client.panoptes.PanoptesAPIException: Received HTTP status code 504 from API

I think removing the default scope in https://github.com/zooniverse/Panoptes/pull/2061 will help but I haven't tested this yet.

**Comment by astopy** [comment]
I'm not sure about this. I think we could do a better job of abstracting away the API details so people don't have to deal with `SetMemberSubject` directly, otherwise it's just going to be confusing (we shouldn't expect people to know when to use one or the other, and it's not clear from the name what a "set member subject" actually is).

If the SMS API call is quicker then we should use that in `SubjectSets.subjects()` rather than having a second method, maybe returning a subclass of `PanoptesObject` that just gets instantiated from the ID and lazy loads the object if/when needed. Or even change `PanoptesObject` itself so that it works that way. I'll need to think about this some more.

**Comment by camallen** [comment]
I agree on hiding the internals but disagree on not having this exposed in anyway as it's a first class resource in the API, that said i've only got 1 use case in my mind currently (setting priority field for ordered sets). 

It's a much faster lookup as it's a straight index and no join filtering and i'd be happy to rework to the suggested changes re lazy loading. Any examples about lazy loading / can you leave some code comments inline?

**Comment by astopy** [comment]
Sure, it's a good idea to have the class in the client somewhere if there's a use case for it, but we shouldn't be expecting people to know what it is or use it directly -- the intended audience for this client are project owners/collaborators, so we shouldn't require people to know any more about Panoptes than they'd learn from using the project builder in PFE.

Here's what I suggest:

- Remove the `SetMemberSubject` import  from `__init__.py` since it's only going to be used internally by the client
- Remove `SubjectSet.set_member_subjects()`
- Rewrite `SubjectSet.subjects()` to use `SetMemberSubject.where()` and return a [generator](https://docs.python.org/3/tutorial/classes.html#generators) to yield one `Subject` at a time
- Modify `PanoptesObject.__init__()` to optionally take an object ID, and modify `PanoptesObject.__getattr__()` and `PanoptesObject.__setattr__()` to do something equivalent to `self.set_raw(self.find(self.object_id).raw)` if needed.

I _think_ that will mean that `SubjectSet.subjects()` will seamlessly continue to work exactly the same while using the faster method.

**Pull request closed without merging**
