### PR TITLE
Allow unretiring subjects

### PR DESCRIPTION
**Pull request by yuenmichelle1**
**Changes**
- adding logic to unretire by subject ids
- adding logic t ounretire by subject set id

### CODE REVIEW

**Review by camallen — APPROVED** [review]
LGTM - I assume you've tested this locally with some driver python code?

**Comment by yuenmichelle1** [comment]
> LGTM - I assume you've tested this locally with some driver python code?

@camallen  Yep :) I set the endpoint to connect to staging and tested there on my own private project. Tested cases : 

-  unretire by subject id
- unretire by subject ids
- unretire by Subjects
- unretire by subject set id
- unretire by subject set ids
- uretire by SubjectSets

**Comment by lcjohnso** [comment]
@yuenmichelle1 Can you add documentation for this new feature?  An example for retirement and unretirement would be great to add to the [user guide](https://github.com/zooniverse/panoptes-python-client/blob/master/docs/user_guide.rst).

**Review by zwolf — APPROVED** [review]
:shipit: !

**Pull request merged**
