### PR TITLE
Add message to StopIteration

### PR DESCRIPTION
**Pull request by srallen**
This adds a slightly better message for the `StopIteration` exception. Open to suggestion for it. For #36

### CODE REVIEW

**Comment by astopy** [comment]
Ah, that's not quite what I meant. I was actually talking about the `find` method (my fault for linking to the version in master in #36, I've updated the link now). We should catch the `StopIteration` exception [here](https://github.com/zooniverse/panoptes-python-client/blob/67e11e16cd91689e62939a6ba54ff7769259a525/panoptes_client/panoptes.py#L431) and raise a new `PanoptesObjectNotFound` exception or something.

Right now if you call, say, `Subject.find(1234)` it just raises `StopIteration` if subject 1234 doesn't exist, which isn't very helpful in debugging.

**Comment by srallen** [comment]
Ah, yeah, in that case the message should be something like "Resource not found"

**Comment by srallen** [comment]
I've been trying this out and get `PanoptesAPIException` rather than `StopIteration`. There may be a particular circumstance when `StopIteration` is raised?

screen shot 2016-08-29 at 3 52 06 pm

**Comment by astopy** [comment]
Ah, my bad, it's not querying on ID that was the problem, it was querying projects by slug. I didn't read @camallen's backtrace properly:

```
Traceback (most recent call last):
  File "test_panoptes_python_client.py", line 5, in <module>
    project = Project.find(slug='camallen/my-testing-project')
  File "/usr/local/lib/python2.7/dist-packages/panoptes_client/project.py", line 25, in find
    return cls.where(id=id, slug=slug).next()
  File "/usr/local/lib/python2.7/dist-packages/panoptes_client/panoptes.py", line 449, in next
    raise StopIteration
StopIteration
```

I guess if you query by ID the API expects there to be one result and returns a not found if not, but (correctly) doesn't do that when you query by anything else. In that case we should catch the `StopIteration` in [Project.find](https://github.com/zooniverse/panoptes-python-client/blob/master/panoptes_client/project.py#L33).

**Pull request closed without merging**
